spring.application.name=MAPPING_demo
spring.datasource.url=jdbc:mysql://localhost:3306/mapping_db
spring.datasource.username=root
spring.datasource.password=SS2003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true